# Generated by Django 2.2.24 on 2021-07-12 21:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hq', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('directions', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('floor_plan', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('locations', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('routes', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('delivery_areas', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('all_the_things', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='chef',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='chef',
            name='twitter_profile',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='thickness',
            field=models.CharField(choices=[(0, 'thin'), (1, 'thick'), (2, 'deep dish')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='pizzas', to='tests.Topping'),
        ),
    ]
